const DRAGONS = [
    {
        selected: true,
        fighter: false,
        image: 'url("assets/icons/spiked-dragon-head-red.png")',
        sprite: 'url("assets/imgs/red-dragon.png")',
        name: 'Smok',
        race: 'Czerwony Smok',
        level: 1,
        exp: 0,
        hp: 100,
        hpPercent: 100,
        maxHp: 100,
        stamina: 100,
        maxStamina: 100,
        str: 15,
        spd: 10,
        vit: 10,
        def: 10,
        mainAttack: 'Pazury',
        specialAttack: 'Ognisty Oddech',
        skills:[],
    },
    {
        selected: true,
        fighter: false,
        image: 'url("assets/icons/spiked-dragon-head-brown.png")',
        sprite: 'url("assets/imgs/red-dragon.png")',
        name: 'Smok',
        race: 'Brązowy Smok',
        level: 1,
        exp: 0,
        hp: 120,
        hpPercent: 100,
        maxHp: 120,
        stamina: 100,
        maxStamina: 100,
        str: 18,
        spd: 8,
        vit: 16,
        def: 13,
        mainAttack: 'Ugryzienie',
        specialAttack: 'Ryk',
        skills:[],
    },
    {
        selected: true,
        fighter: false,
        image: 'url("assets/icons/spiked-dragon-head-green.png")',
        sprite: 'url("assets/imgs/red-dragon.png")',
        name: 'Smok',
        race: 'Zielony Smok',
        level: 1,
        exp: 0,
        hp: 90,
        hpPercent: 100,
        maxHp: 90,
        stamina: 120,
        maxStamina: 120,
        str: 15,
        spd: 20,
        vit: 9,
        def: 13,
        mainAttack: 'Ogon',
        specialAttack: 'Trujący oddech',
        skills:[],
    },
];